# Generated by Django 3.2.6 on 2023-07-25 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='requests',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.post')),
            ],
        ),
    ]
